### ISSUE TITLE
Create the Polls list page

### ISSUE THREAD

**Issue by Themimitoof** [SN-DAI18-20/Formol#25]

**Comment by Themimitoof** [comment]
Here is a wireframe mockup:
![image](https://user-images.githubusercontent.com/1113348/77946548-c73b5e00-72c2-11ea-9883-9c849f0adde2.png)

Instead of creating the “créer nouveau” button on the right of the page title like the mockup, use instead: https://material-ui.com/components/floating-action-button/

**Comment by stanislas14789** [comment]
Il faudra ajouter les redirection pour les boutons(les fonctions sont à compléter avec) et changer url de call de api pour récupérer les polls.
